# google oauth2 setting
spring:
  security:
    oauth2:
      client:
        # registration
        registration:
          # GOOGLE oauth2 setting
#          google:
#            client-id:
#            client-secret:
#            scope:
#              - profile
#              - email

          # NAVER oauth2 setting
          naver:
            client-id: nOa86RW04YADAuuYBxek
            client-secret: IWFTj2f2Xg
            redirect_uri_template: {baseUrl}/{action}/oauth2/code/{registrationId}
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
            client-name: Naver

        # provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response